### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by marianoguerra** [alii/pathcat#3]
hi the project doesn't have a LICENSE file and doesn't seem to mention the license in the README or package.json

I can open a PR with the license changes if you tell me which one you prefer

**Comment by alii** [comment]
Hi, you're welcome to use pathcat under no license or constraints at all.
If you'd like, you could open a PR with the "unlicense"

https://choosealicense.com/licenses/unlicense/

Thank you :)

**Comment by YurySolovyov** [comment]
https://github.com/alii/pathcat/blob/d03f8710bc0f72bde8b4fa846abd73b5501bdb8b/package.json#L23

**Comment by alii** [comment]
lol oops, unintentional. will fix😅

**Comment by alii** [comment]
https://github.com/alii/pathcat/commit/b98e0256a38df58e79b319a66de50acaeef46f0c
